######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 26 16:04:08 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
