######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 26 14:00:32 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
